// Mocks generated by Mockito 5.4.4 from annotations
// in x_video_ai/test/services/video_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:convert' as _i8;
import 'dart:typed_data' as _i5;

import 'package:cross_file/src/types/interface.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:x_video_ai/gateway/ffmpeg.dart' as _i4;
import 'package:x_video_ai/gateway/file_getaway.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFileWrapper_0 extends _i1.SmartFake implements _i2.FileWrapper {
  _FakeFileWrapper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDirectoryWrapper_1 extends _i1.SmartFake
    implements _i2.DirectoryWrapper {
  _FakeDirectoryWrapper_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FileGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileGateway extends _i1.Mock implements _i2.FileGateway {
  MockFileGateway() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FileWrapper getFile(String? path) => (super.noSuchMethod(
        Invocation.method(
          #getFile,
          [path],
        ),
        returnValue: _FakeFileWrapper_0(
          this,
          Invocation.method(
            #getFile,
            [path],
          ),
        ),
      ) as _i2.FileWrapper);

  @override
  _i3.Future<void> createDirectory(String? path) => (super.noSuchMethod(
        Invocation.method(
          #createDirectory,
          [path],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i2.DirectoryWrapper getDirectory(String? path) => (super.noSuchMethod(
        Invocation.method(
          #getDirectory,
          [path],
        ),
        returnValue: _FakeDirectoryWrapper_1(
          this,
          Invocation.method(
            #getDirectory,
            [path],
          ),
        ),
      ) as _i2.DirectoryWrapper);
}

/// A class which mocks [FFMpeg].
///
/// See the documentation for Mockito's code generation for more information.
class MockFFMpeg extends _i1.Mock implements _i4.FFMpeg {
  MockFFMpeg() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> processVideo({
    required String? inputPath,
    required String? outputPath,
    required String? format,
    bool? sound = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processVideo,
          [],
          {
            #inputPath: inputPath,
            #outputPath: outputPath,
            #format: format,
            #sound: sound,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.Uint8List?> generateThumbnail({
    required String? outputPath,
    required String? inputFile,
    String? filename = r'thumbnail',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateThumbnail,
          [],
          {
            #outputPath: outputPath,
            #inputFile: inputFile,
            #filename: filename,
          },
        ),
        returnValue: _i3.Future<_i5.Uint8List?>.value(),
      ) as _i3.Future<_i5.Uint8List?>);

  @override
  _i3.Future<Map<String, dynamic>> getVideoInformation(String? inputPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoInformation,
          [inputPath],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [XFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockXFile extends _i1.Mock implements _i6.XFile {
  MockXFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i3.Future<void> saveTo(String? path) => (super.noSuchMethod(
        Invocation.method(
          #saveTo,
          [path],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> length() => (super.noSuchMethod(
        Invocation.method(
          #length,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String> readAsString(
          {_i8.Encoding? encoding = const _i8.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsString,
          [],
          {#encoding: encoding},
        ),
        returnValue: _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #readAsString,
            [],
            {#encoding: encoding},
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<_i5.Uint8List> readAsBytes() => (super.noSuchMethod(
        Invocation.method(
          #readAsBytes,
          [],
        ),
        returnValue: _i3.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
      ) as _i3.Future<_i5.Uint8List>);

  @override
  _i3.Stream<_i5.Uint8List> openRead([
    int? start,
    int? end,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #openRead,
          [
            start,
            end,
          ],
        ),
        returnValue: _i3.Stream<_i5.Uint8List>.empty(),
      ) as _i3.Stream<_i5.Uint8List>);

  @override
  _i3.Future<DateTime> lastModified() => (super.noSuchMethod(
        Invocation.method(
          #lastModified,
          [],
        ),
        returnValue: _i3.Future<DateTime>.value(_FakeDateTime_2(
          this,
          Invocation.method(
            #lastModified,
            [],
          ),
        )),
      ) as _i3.Future<DateTime>);
}
