name: Run Tests

on:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.5

      - run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build macOS app
        run: flutter build macos --release

      - name: Fix permissions
        run: chmod -R +x build/macos/Build/Products/Release/x_video_ai.app/Contents/MacOS/*

      - name: Create ZIP of Release directory
        run: |
          cd build/macos/Build/Products/
          zip -r x_video_ai.zip x_video_ai.app

      - name: Upload macOS app ZIP
        uses: actions/upload-artifact@v3
        with:
          name: macOS-app
          path: build/macos/Build/Products/x_video_ai.zip