name: Run Tests

on:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.5

      - run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - run: flutter build macos --release

      - name: Upload macOS build artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS-app
          path: build/macos/Build/Products/Release/